schema_version = "1.0.0"

id = "sejfo_robotics_utility_and_manipulator"
version = "0.2.1"
name = "SeRUM"
tagline = "Import and translate robot language code into animations"
maintainer = "Andreas Wetter <andreas.wetter@sejfo.se>"
type = "add-on"

blender_version_min = "4.2.0"

license = [
    "SPDX:GPL-3.0-or-later",
]